#include <iostream.h>
#include <conio.h>
 void main()
 {

   clrscr();

   double darse1,darse2,darse3;

   cout<<"nomreye darse1 ra vared kon..."<<endl;

   cin>>darse1;

   cout<<"nomreye darse2 ra vared kon..."<<endl;

   cin>>darse2;

   cout<<"nomreye darse3 ra vared kon..."<<endl;

   cin>>darse3;

   double sum = darse1+darse2+darse3;

   double moadel= sum / 3;

   cout<<"Moadel::  "<<moadel;

   getch();
 }
